// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmaRkwjoBQO-ARgdvKjmq_wlx5URLb2Hs',
    appId: '1:687683938070:web:67fcedbb1ec1b5cc46d237',
    messagingSenderId: '687683938070',
    projectId: 'ev-ici-denge',
    authDomain: 'ev-ici-denge.firebaseapp.com',
    storageBucket: 'ev-ici-denge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZpNi3uzj5fYT4P9T3wMsKA_EmfEIxcdo',
    appId: '1:687683938070:android:4d800fa0fc470d9a46d237',
    messagingSenderId: '687683938070',
    projectId: 'ev-ici-denge',
    storageBucket: 'ev-ici-denge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR3eP0oDb52edgy1Zw_MIT69HZLsv9Fb8',
    appId: '1:687683938070:ios:5a130bccfd4fe37046d237',
    messagingSenderId: '687683938070',
    projectId: 'ev-ici-denge',
    storageBucket: 'ev-ici-denge.firebasestorage.app',
    iosBundleId: 'com.example.evIciDenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR3eP0oDb52edgy1Zw_MIT69HZLsv9Fb8',
    appId: '1:687683938070:ios:5a130bccfd4fe37046d237',
    messagingSenderId: '687683938070',
    projectId: 'ev-ici-denge',
    storageBucket: 'ev-ici-denge.firebasestorage.app',
    iosBundleId: 'com.example.evIciDenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmaRkwjoBQO-ARgdvKjmq_wlx5URLb2Hs',
    appId: '1:687683938070:web:18f6871000f8019946d237',
    messagingSenderId: '687683938070',
    projectId: 'ev-ici-denge',
    authDomain: 'ev-ici-denge.firebaseapp.com',
    storageBucket: 'ev-ici-denge.firebasestorage.app',
  );
}
